# Generated by Django 2.1.1 on 2018-10-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20181011_1806'),
        ('course', '0002_auto_20180927_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ourse_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='所属机构'),
        ),
    ]
