# Generated by Django 2.1.1 on 2018-09-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180926_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerlfyRecord',
            new_name='EmailVerifyRecord',
        ),
    ]
