# Generated by Django 2.1.1 on 2018-10-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20180926_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='used',
            field=models.BooleanField(default=False, help_text=('验证码已经用过？',), verbose_name='已使用'),
        ),
    ]
